# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "goto"
license = "MIT"
licenselink = "https://github.com/nevivurn/goto-hugo/blob/master/LICENSE"
description = "A minimal hugo theme."
homepage = "https://www.nevivur.net/"
tags = ["minimal", "blog"]
features = []
min_version = "0.41"

[author]
  name = "Yongun Seong"
  homepage = "https://www.nevivur.net/"
