baseURL = "https://www.nevivur.net/"
languageCode = "en-us"
title = "goto now;"
theme = "nevi"

disableKinds = ["taxonomy", "taxonomyTerm"]

[permalinks]
posts = "/:year/:month/:title/"

[[menu.main]]
name = "About"
url = "about/"
weight=1

[[menu.main]]
name = "Github"
url = "https://github.com/nevivurn"
weight=2

[params]
copyright = "&copy; Yongun Seong. Licensed under [CC-BY 4.0](https://creativecommons.org/licenses/by/4.0/)."
styledTitle = "`goto now;`"
notFound = """
```
You step in the stream,
but the water has moved on.
This page is not here.
```"""
