baseURL = "https://www.nevivur.net/"
languageCode = "en-us"
title = "goto now;"
copyright = "Licensed under Creative Commons Attribution 4.0."

pygmentsCodefences = true
pygmentsStyle = "solarized-light"
pygmentsUseClasses = true

disableKinds = ["taxonomy", "taxonomyTerm", "sitemap"]

[author]
name = "Yongun Seong"
email = "nevivurn@riseup.net"

[permalinks]
posts = "/:year/:month/:title/"

[outputs]
home = ["HTML"]
section = ["HTML", "RSS"]
page = ["HTML"]

[[menu.main]]
name = "Github"
url = "https://github.com/nevivurn"
weight=1001

[params]
styledTitle = "`goto now;`"
notFound = """
```
You step in the stream,
but the water has moved on.
This page is not here.
```"""
