baseURL = "https://www.nevivur.net/"
languageCode = "en-us"
title = "goto now;"
copyright = "Licensed under [Creative Commons Attribution 4.0](https://creativecommons.org/licenses/by/4.0/)."
theme = "goto"

pygmentsCodefences = true
pygmentsStyle = "bw"
pygmentsUseClasses = true

disableKinds = ["sitemap", "RSS"]

[blackfriday]
hrefTargetBlank = true
extensions = ["tabSizeEight"]

[author]
name = "Yongun Seong"
email = "nevivurn@riseup.net"

[permalinks]
posts = "/posts/:year/:month/:title/"
writeups = "/writeups/:year/:month/:title/"

[taxonomies]
tag = "tags"

[outputs]
home = ["HTML"]
section = ["HTML", "RSS"]
page = ["HTML"]

[params]
styledTitle = "`goto now;`"
notFound = """
```
You step in the stream,
but the water has moved on.
This page is not here.
```"""
